// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/proto.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9897619deba694d0, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9897619deba694d0, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SentEventRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SentEventRequest) Reset()         { *m = SentEventRequest{} }
func (m *SentEventRequest) String() string { return proto.CompactTextString(m) }
func (*SentEventRequest) ProtoMessage()    {}
func (*SentEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9897619deba694d0, []int{2}
}
func (m *SentEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SentEventRequest.Unmarshal(m, b)
}
func (m *SentEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SentEventRequest.Marshal(b, m, deterministic)
}
func (m *SentEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentEventRequest.Merge(m, src)
}
func (m *SentEventRequest) XXX_Size() int {
	return xxx_messageInfo_SentEventRequest.Size(m)
}
func (m *SentEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SentEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SentEventRequest proto.InternalMessageInfo

func (m *SentEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SentEventResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SentEventResponse) Reset()         { *m = SentEventResponse{} }
func (m *SentEventResponse) String() string { return proto.CompactTextString(m) }
func (*SentEventResponse) ProtoMessage()    {}
func (*SentEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9897619deba694d0, []int{3}
}
func (m *SentEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SentEventResponse.Unmarshal(m, b)
}
func (m *SentEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SentEventResponse.Marshal(b, m, deterministic)
}
func (m *SentEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentEventResponse.Merge(m, src)
}
func (m *SentEventResponse) XXX_Size() int {
	return xxx_messageInfo_SentEventResponse.Size(m)
}
func (m *SentEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SentEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SentEventResponse proto.InternalMessageInfo

func (m *SentEventResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "cloud_worker.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "cloud_worker.HelloReply")
	proto.RegisterType((*SentEventRequest)(nil), "cloud_worker.SentEventRequest")
	proto.RegisterType((*SentEventResponse)(nil), "cloud_worker.SentEventResponse")
}

func init() { proto.RegisterFile("proto/proto.proto", fileDescriptor_9897619deba694d0) }

var fileDescriptor_9897619deba694d0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x07, 0x93, 0x7a, 0x60, 0x52, 0x88, 0x27, 0x39, 0x27, 0xbf, 0x34, 0x25, 0xbe, 0x3c,
	0xbf, 0x28, 0x3b, 0xb5, 0x48, 0x49, 0x89, 0x8b, 0xc7, 0x23, 0x35, 0x27, 0x27, 0x3f, 0x28, 0xb5,
	0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x33, 0x08, 0xcc, 0x56, 0x52, 0xe3, 0xe2, 0x82, 0xaa, 0x29, 0xc8, 0xa9, 0x14, 0x92,
	0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x87, 0x29, 0x82, 0x71, 0x95, 0xd4, 0xb8, 0x04,
	0x82, 0x53, 0xf3, 0x4a, 0x5c, 0xcb, 0x52, 0xf3, 0x4a, 0xf0, 0x99, 0xa7, 0xce, 0x25, 0x88, 0xa4,
	0xae, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0x9b, 0x42, 0xa3, 0xd9, 0x8c, 0x5c, 0x6c, 0xe1, 0x60,
	0x77, 0x0a, 0x39, 0x71, 0x71, 0x04, 0x27, 0x56, 0x82, 0x9d, 0x21, 0x24, 0xa5, 0x87, 0xec, 0x05,
	0x3d, 0x64, 0xf7, 0x4b, 0x49, 0x60, 0x95, 0x2b, 0xc8, 0xa9, 0x54, 0x62, 0x10, 0xf2, 0xe5, 0xe2,
	0x0c, 0x4e, 0xcd, 0x4b, 0x01, 0xdb, 0x2b, 0x24, 0x87, 0xaa, 0x10, 0xdd, 0xe1, 0x52, 0x04, 0xe4,
	0x95, 0x18, 0x9c, 0xc4, 0xb9, 0x58, 0xc1, 0x21, 0xea, 0xc4, 0x1a, 0x00, 0xa2, 0x02, 0x18, 0xa3,
	0x20, 0xfc, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x32, 0x06, 0xbf, 0xb1,
	0x7d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Send A Event
	SendEvent(ctx context.Context, in *SentEventRequest, opts ...grpc.CallOption) (*SentEventRequest, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/cloud_worker.Worker/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) SendEvent(ctx context.Context, in *SentEventRequest, opts ...grpc.CallOption) (*SentEventRequest, error) {
	out := new(SentEventRequest)
	err := c.cc.Invoke(ctx, "/cloud_worker.Worker/SendEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Send A Event
	SendEvent(context.Context, *SentEventRequest) (*SentEventRequest, error)
}

// UnimplementedWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (*UnimplementedWorkerServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedWorkerServer) SendEvent(ctx context.Context, req *SentEventRequest) (*SentEventRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_worker.Worker/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SentEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_worker.Worker/SendEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).SendEvent(ctx, req.(*SentEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud_worker.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Worker_SayHello_Handler,
		},
		{
			MethodName: "SendEvent",
			Handler:    _Worker_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
